inherit_from: 
  - config/rubocop/include.yml
  - config/rubocop/exclude.yml
  - config/rubocop/exclude.yml

# Offense count: 1
# Configuration parameters: CountComments.
Style/ClassLength:
  Max: 160

# Offense count: 3
Style/CyclomaticComplexity:
  Max: 9
