AllCops:
  Exclude:
    - 'tmp/**/*'

# Offense count: 1
# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

# Offense count: 8
# Configuration parameters: CountComments.
Style/MethodLength:
  Max: 118

# Offense count: 1
# Configuration parameters: CountComments.
Style/ClassLength:
  Max: 160
  Exclude:
    - 'lib/middleman-presentation/cli/create_presentation.rb'

# Offense count: 3
Style/CyclomaticComplexity:
  Max: 9
  Exclude:
    - 'lib/middleman-presentation/file_extensions.rb'
