#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'addressable/uri'
require 'middleman/presentation/application_config'

config = Middleman::Presentation::ApplicationConfig.new(merge_files: true, safe: true)

uri = Addressable::URI.parse("http://#{config.network_interface}:#{config.network_port}")

options = OpenStruct.new
options.listen = uri
options.verbose = false

OptionParser.new do |opts|
  opts.banner = 'Usage: script/start [options]'

  opts.on('-p PORT', '--network-port PORT', 'Port to listen on') do |p|
    options.listen.port = p
  end

  opts.on('-i INTERFACE', '--network-interface INTERFACE', 'Interface to listen on') do |h|
    options.listen.interface = h
  end

  opts.on('-d', '--debug-mode', 'Debug mode') do |_h|
    options.debug_mode = true
  end

end.parse!

launchy_pid = fork do
  system("bundle exec launchy #{options.listen}")
end

Process.waitpid(launchy_pid)

command = []
command << 'bundle exec'
command << 'middleman-presentation serve'
command << "--network-port #{options.listen.port}"
command << "--network-interface #{options.listen.interface}"
command << '--debug-mode' if options.debug_mode

system(command.join(' '))
