#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'addressable/uri'

uri = Addressable::URI.parse('http://127.0.0.1:1234')

options = OpenStruct.new
options.listen = uri
options.verbose = false

OptionParser.new do |opts|
  opts.banner = 'Usage: script/start [options]'

  opts.on('-p PORT', '--network-port PORT', 'Port to listen on') do |p|
    options.listen.port = p
  end

  opts.on('-i INTERFACE', '--network-interface INTERFACE', 'Interface to listen on') do |h|
    options.listen.interface = h
  end

  opts.on('-d', '--debug-mode', 'Debug mode') do |_h|
    options.debug_mode = true
  end

  opts.on('-o', '--open-in-browser', 'Open presentation in browser') do |_h|
    options.open_in_browser = true
  end

end.parse!

command = []
command << 'bundle exec'
command << 'middleman-presentation serve'
command << "--network-port #{options.listen.port}"
command << "--network-interface #{options.listen.interface}"
command << "--open-in-browser" if options.open_in_browser
command << '--debug-mode' if options.debug_mode

system(command.join(' '))
