# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

gem 'middleman-presentation', path: File.expand_path('../../../../', __FILE__)

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'pry-byebug'
end

gem 'kramdown'
gem 'github-markup'
gem 'liquid'
gem 'rake'
