#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'presentation/helper'
include Presentation::Helper

install_gem 'bundler'
install_gem 'middleman'

run_task 'presentation:bootstrap'
