#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'presentation/helper'

gem_install 'bundler'
gem_install 'middleman'

run_task 'presentation:bootstrap'
