#!/usr/bin/env ruby

require 'logger'

def logger
  @logger ||= Logger.new($stderr)
end

def require_gem(require_files, gem_name)
tries = 3

begin
  require_files.each do |f|
    require f
  end
rescue
  tries -= 1

  if tries > 0

    logger.info "Installing \"#{gem_name}\" gem."
    system("gem install #{gem_name}")

    retry
  else
    logger.fatal "You need to install \"#{gem_name}\". I tried it #{tries} times, but was not successful."
    exit 1
  end
end
end

require_gem(
  %w[
  thor
  thor/group
  thor/actions
  ], 'thor'
)

require_gem([], 'bundler')


class Cli < Thor::Group
  include Thor::Actions

  no_commands {
    def self.source_root
      File.expand_path('../../', __FILE__)
    end

    def clone_repository(source, destination)
      system("git clone #{source} #{File.join(self.class.source_root, destination)}")
    end

    def sources_directory
      File.join(self.class.source_root, 'sources')
    end

    def source_file(file)
      File.join(sources_directory, file)
    end

    def root_file(file)
      File.join(self.class.source_root, file)
    end

  }

  def install_software
    run 'bundle install'
  end

  def cleanup_middleman
    remove_dir 'sources/'
  end

  def clone_reveal_js
    clone_repository('http://github.com/hakimel/reveal.js.git', 'sources')
  end

  def cleanup_reveal_js
    FileUtils.mv source_file('index.html'), source_file('documentation.html')
  end

  def create_slides_directory
    empty_directory 'sources/slides'
  end

  def create_layouts_directory
    empty_directory 'sources/layouts'
  end

  def create_application_layout_file
    copy_file 'templates/layout.erb', source_file('layout.erb')
  end

  def copy_index_html_template
    copy_file 'templates/index.html.erb', source_file('index.html.erb')
  end

  def copy_gitignore
    copy_file 'templates/.gitignore', root_file('.gitignore')
  end

end

Cli.start
