#!/usr/bin/env ruby

require_relative '_base'

require_gem(
  %w[
  thor
  thor/group
  thor/actions
  ], 'thor'
)

require_gem([], 'middleman')
require_gem([], 'bundler')

class Cli < Thor::Group
  include Thor::Actions

  def build_presentation
    Dir.chdir File.expand_path('../../source', __FILE__) do
      run 'middleman build'
    end
  end
end

Cli.start
