#!/usr/bin/env rake

require 'filegen'
require 'fedux_org_stdlib/rake_tasks/webserver'
require 'fedux_org_stdlib/rake_tasks/gems'
require 'fedux_org_stdlib/rake_tasks/software_version/bump'
require 'active_support/all'
require 'open3'

require 'coveralls/rake/task'
Coveralls::RakeTask.new

desc 'Run test suite'
task test: ['test:rspec', 'test:rubocop', 'test:cucumber']

namespace :test do
  desc 'Test with coveralls'
  task coveralls: ['test', 'coveralls:push']

  task :rubocop do
    sh 'bundle exec rubocop'
  end

  task 'rubocop:autocorrect' do
    sh 'bundle exec rubocop --auto-correct'
  end

  desc 'Run rspec'
  task :rspec do
    sh 'bundle exec rspec'
  end

  desc 'Run cucumber'
  task :cucumber do
    sh 'bundle exec cucumber -p all'
  end

  task :parallel_cucumber do
    sh 'bundle exec parallel_cucumber features -o "-p all" --serialize-stdout'
  end

  desc 'Run mutant'
  task :mutant do
    sh 'mutant --include lib --require middleman-presentation --use rspec "Middleman::Presentation*"'
  end
end

namespace :gem do
  desc 'Clean build packages'
  task :clean do
    FileUtils.rm Dir.glob(File.join(pkg_directory, '*.gem'))
  end
end

task 'gem:build' => 'webserver:fetch'
