#!/usr/bin/env ruby

require 'thor'
require 'thor/group'
require 'thor/actions'

class Cli < Thor::Group
  include Thor::Actions

  no_commands {
    def self.source_root
      File.expand_path('../../', __FILE__)
    end

    def clone_repository(source, destination)
      system("git clone #{source} #{File.join(self.class.source_root, destination)}")
    end

    def sources_directory
      File.join(self.class.source_root, 'sources')
    end

    def source_file(file)
      File.join(sources_directory, file)
    end

  }

  def cleanup_middleman
    remove_dir 'sources/'
  end

  def clone_reveal_js
    clone_repository('http://github.com/hakimel/reveal.js.git', 'sources')
  end

  def cleanup_reveal_js
    FileUtils.mv source_file('index.html'), source_file('documentation.html')
  end

  def create_slides_directory
    empty_directory 'sources/slides'
  end

  def create_layouts_directory
    empty_directory 'sources/layouts'
  end

  def create_application_layout_file
    copy_file 'templates/layout.erb', source_file('layout.erb')
  end

  def copy_index_html_template
    copy_file 'templates/index.html.erb', source_file('index.html.erb')
  end
end

Cli.start
