#!/bin/bash

set -e

function output_error_log {
  [[ -f error.log ]] && ( cat error.log >&2; rm error.log)
}

echo -n '[CHECK] ruby installed? '
which 'ruby' >/dev/null 2>error.log || ( echo -e "FAILED\n\nCould not find \`ruby\`. Please install ruby or add it to PATH"; output_error_log; exit 1 )
echo OK

echo -n '[INSTALL] rubygem "rake" '
gem install rake >/dev/null 2>error.log || ( echo -e "FAILED\n\nAn error occurred during installation of rake. Run \`gem install rake\` yourself."; output_error_log; exit 1 )
echo OK

if [ -n "$CI" ]; then
  rake_task='bootstrap:ci'
else
  rake_task='bootstrap'
fi

echo -n "[RAKE] $rake_task "
rake $rake_task
#rake $rake_task >/dev/null 2>error.log || ( echo -e "FAILED\n\nAn error occurred during run of rake-task \"$rake_task\". Run \`rake $rake_task\` yourself."; output_error_log; exit 1 )
echo OK
